id: P009078
initial_creation_type: ocr
source_metadata:
  id: bdr:W21658
  title: གསོ་བྱ་ལུས་ཀྱི་རྣམ་བཤད
  author: ''
  volumes:
    81186a1156984891b3efd4c15f451647:
      image_group_id: I4795
      title: ''
      volume_number: 1
      total_pages: 218
